### ISSUE TITLE
`brewdo do` has trouble with commands relying on $PWD?

### ISSUE THREAD

**Issue by telemachus** [zigg/brewdo#7]
In the past few weeks, I've noticed that `brewdo do [command arg arg...]` sometimes fails in surprising ways.

Two examples:

    $ brewdo do luarocks build
    Error: Argument missing. See '/usr/local/bin/luarocks help build'.

    $ brewdo do make install
    make: *** No rule to make target `install'.  Stop.

In both cases, `sudo luarocks build` or `sudo make install` worked as expected.

The problem seems to be that the command that gets passed along relies on items in the user's `$PWD`, but `brewdo` has moved out of that directory.

**Comment by telemachus** [comment]
Ping @zigg -- Just checking in since I was reminded of this issue today. Any further thoughts about how to make `brewdo` comfortable with commands that rely on `$PWD`?

**Comment by zigg** [comment]
I think what needs to be done here is that brewdo must check to make sure the sandbox user account can actually use the current working directory, then conditionally remain in that directory or change to the root depending on whether it can.  The original change-to-root functionality was added because we couldn't use brewdo from directories where the sandbox user didn't have rights to be.

**Comment by telemachus** [comment]
Ok. I'm not entirely sure how this would look in "idiomatic" Ruby (a `chdir` wrapped in a `begin...rescue`?), but I'll think about that. Thanks for the thought.

**Comment by zigg** [comment]
Give this branch a shot: https://github.com/zigg/brewdo/tree/feature/preserve-working-directory

**Comment by telemachus** [comment]
Good news/bad news. It still throws an error, but now it's a *new* error.

    $ brewdo do luarocks-5.2 make 
    mkdir: /usr/local/lib/luarocks/rocks-5.2/utilitybelt/0.3-1/lib: Permission denied
    
    Error: failed making directory /usr/local/lib/luarocks/rocks-5.2/utilitybelt/0.3-1/lib

I'm guessing that this is because `brewdo do` is failing to escalate privileges as it should?

**Comment by zigg** [comment]
Who owns that tree right now?  Maybe it's owned by your user account instead of the sandbox user after your prior experimentation?

**Comment by telemachus** [comment]
Sigh. Duh. Let me check, be right back.

**Comment by telemachus** [comment]
We have a winner! That seems to work perfectly. Thanks so much.

    $ brewdo do luarocks-5.2 make 
    Updating manifest for /usr/local/lib/luarocks/rocks-5.2
    utilitybelt 0.3-1 is now built and installed in /usr/local (license: BSD)

**Comment by zigg** [comment]
Awesome!  Since it's a behavior change (however slight), I'll merge that into version 2.0.  Thanks for your patience and your testing 😊
